version: "3.9"

services:
  api:
    container_name: gpci_compro_api
    image: gpci-api:latest
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: unless-stopped

  worker:
    container_name: gpci_compro_worker
    image: gpci-api:latest
    build: .
    command: ["/app/worker"]
    env_file:
      - .env
    restart: unless-stopped

  migrator:
    container_name: gpci_migrator
    image: golang:1.22-alpine
    working_dir: /app
    command: >
      sh -c "go run ./cmd/api -migrate-only"
    volumes:
      - ./:/app
    env_file:
      - .env
    profiles:
      - migrate
